### register
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
   "username": "username2",
   "password": "pass1"
}

### login
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
   "username": "username2",
   "password": "pass1"
}

### index page
GET http://localhost:3000/api

### index page
GET http://localhost:3000/api/user/list

### secret route
GET http://localhost:3000/api/secret


### create todos
POST http://localhost:3000/api/todos
Content-Type: application/json

{
   "todo": "Code project5"
}

### fetch all todos
GET http://localhost:3000/api/todos/list
